services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8848:8848"
    volumes:
      - ./backend:/app
      - ./data:/data  # Mount the directory containing geo_AW3D30.vrt
    environment:
      - FLASK_ENV=production
      - ALOS_DSM_PATH=/data/geo_AW3D30.vrt

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Using the production Dockerfile
    ports:
      - "80:80"  # Expose on port 80 instead of 5173
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8848
