version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5001:5000" # Exposing backend to 5001 to avoid conflict if local Flask runs on 5000
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev # We will create this Dockerfile next
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    stdin_open: true # For react-scripts
    tty: true # For react-scripts
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true # For hot reloading in Docker 